server:
  port: 8081

spring:
  application:
    name: sso
  redis:
    host: 172.18.36.120
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com.su: DEBUG
#    org.springframework.security: INFO
#  file: /var/log/java/sso.log

wechat:
  appId: 12345
  appSecret: '{cipher}8742583da780b5994db1ed4f56dd5736205b3ce47b65ad5c8a6ab7a7e2d9a88e'