server:
  port: 8081

spring:
  application:
    name: sso
  redis:
    host: 172.18.36.120
    database: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka/

logging:
  level:
    com.su: DEBUG
    org.springframework.security: INFO
#  file: /var/log/java/sso.log